### ISSUE TITLE
feat: direct messages

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/protocol#5]
We plan to introduce a Direct Messaging system in Farcaster for users to communicate individually and in groups. Philosophically, we want this system to be as secure as the Signal protocol. It should guarantee: 

- **end-to-end encryption**: messages are encrypted before leaving a device and decrypted only at the recipient device. 
- **forward secrecy**:  the compromise of a previous key-pair does not compromise future communications
- **break-in recovery**:  the system can recovery safely and easily from a compromise of a key-pair
- **minimal metadata leakage**: we minimize the amount of metadata that can be determined about a user
- **anti-forgery**: users cannot impersonate each other

The purpose of this ticket is to outline our approach with enough detail that we are confident that it can easily be added to our protocol in the future. It is not meant to be exhaustive or to cover narrow casts (casts encrypted to a narrow audience) which is a slightly different feature with different requirements. We may also choose to build this feature in stages, starting with no encryption and eventually tending towards a highly secure system that meets our requirements. 

### 1: Quick & Dirty Elliptic Curve Encryption 

Users can communicate securely by using ECDH to derive a shared secret which in turns created a shared symmetric encryption key. Farcaster messages are authenticated by default with signatures, so another MAC system is not required. Currently, all devices have the same ECC key-pair which makes cross device communication straightforward. 

A mailbox server can be implemented to proxy messages between users and it holds on to messages for at least N days to ensure that it is delivered to all devices. There is no guarantee that every device gets every messages, if it does not come online within that timeframe. 

This approach has many drawbacks - it has no forward secrecy or break-in recovery, it is vulnerable to determined attackers who collect large volumes of ciphertext and it leaks metadata to any listener. It is also only possible in the current Farcaster v1 system where all clients store the same ECC key, and will need to be deprecated as we move to v2. Its only benefit is that it is significantly faster to implement than any of the other options. The only reason to consider this approach is to ship a quick v1 of the system to get usage in a beta form, where users are made aware that the encryption is not fully trustworthy yet. 

### 2: Modified Double Ratchet

We implement the  the Signal protocol using Double Ratchet, X3DH and Sesame. We may even be able to use Farcaster Hub network to augment the Sesame mailbox system to offer even less metadata leakage. This achieves all of our goals and is a theoretically secure and practically tested framework. The primary downside to this approach is that it is a significant amount of work to implement correctly, and there is room for errors which can lead to comprise. 

### 3: Matrix Client

Instead of building our own communication stack, we can use [Matrix](https://matrix.org/) which offers an opinionated stack for real-time communication. The primary downside is the lack of flexibility and extra infrastructure we need to run. We may have to run a Matrix home server for each user, in addition to a Farcaster Hub or sufficiently modify the Hub to perform both functions. This area is less clear and needs more research. 

## Implications for Current Implementation

The good news is that the decisions we are making with how to handle keys have very little impact on the correct long term designs (2, 3) though they make (1) a little harder in the short term. We should proceed with implementation and revisit this as we get closer to considering DM's

## References

- **[ECDH Key Exchange](https://cryptobook.nakov.com/asymmetric-key-ciphers/ecdh-key-exchange)**
- **[ECC Encryption / Decryption](https://cryptobook.nakov.com/asymmetric-key-ciphers/ecc-encryption-decryption)**
- **[Signal's Double Ratchet Algorithm](https://signal.org/docs/specifications/doubleratchet/)**
- **[E2E encryption in Matrix](https://www.uhoreg.ca/blog/20170910-2110)**
-  **[Wickr Messaging Protocol](https://wickr.com/wickrs-messaging-protocol/)**
- **[X3DH Key Agreement protocol](https://signal.org/docs/specifications/x3dh/)**
- **[Sesame Algorithm](https://signal.org/docs/specifications/sesame/)**

**Comment by gsgalloway** [comment]
Another thing to consider, and this is a point where I think Farcaster can do _better_ than Signal, is the way in which two users will mutually authenticate before they establish an encrypted DM session. Signal's approach to the key distribution problem puts Signal as essentially a root CA that can MitM anyone if they wanted, and then users can additionally decide to vet each others' "security numbers" to catch if a MitM happened (which they won't bother to do, because it's a hidden feature and they have no idea that they're supposed to do this). [More details](https://sequoia-pgp.org/blog/2021/06/28/202106-hey-signal-great-encryption-needs-great-authentication/#:~:text=Signal's%20default%20authentication%20mechanism%20uses,That%20completes%20the%20verification.). Telegram has a similar approach and lets users opt in to checking each others' visualization of their auth keys.

In Farcaster's case each client could use their counterparty's custody key as the root of trust with which to verify the user's auth credentials. Compared to the status quo, this removes Farcaster's hosted services as a root of trust and instead introduces the client's Ethereum node as a new root of trust (to accurately report the DM counterparty's custody key). This in turn is much more easily hardened by having the client ask multiple nodes for their counterparty's custody key and check for consensus among the replies.

I thin initial implementation for auth should look close to its final implementation, and I agree it's OK to let the solution for privacy start out simpler and then become more complex and hardened later on.

Might also be important to establish the precedent early if we expect secret DMs eventually won't be able to be synced between a user's different devices.

**Comment by gsgalloway** [comment]
You should be able to achieve forward secrecy in another quick & dirty approach by swapping out ECDH for ECDHE. Create a new ephemeral ECDH key pair each time you start a new session with the same user and have it be signed by your static key.

As soon as you do that though you would lose the ability to do cross-device communication within the same encrypted session (I believe this will be unavoidable with any solution that achieves forward secrecy)

**Comment by galligan** [comment]
Love that y'all are thinking about this, and how to bring secure messaging to Farcaster! It would be great to dig in with you around this as we've been hard at work on this with [XMTP](https://github.com/xmtp).

The biggest outright advantage that we might be able to achieve in working on this together, would be that DMs could be accessible through other clients building with XMTP too.

**Comment by CassOnMars** [comment]
> You should be able to achieve forward secrecy in another quick & dirty approach by swapping out ECDH for ECDHE. Create a new ephemeral ECDH key pair each time you start a new session with the same user and have it be signed by your static key.
> 
> As soon as you do that though you would lose the ability to do cross-device communication within the same encrypted session (I believe this will be unavoidable with any solution that achieves forward secrecy)

You can alter the approach, using a 2-of-n asynchronous threshold key generation protocol (https://eprint.iacr.org/2021/1591.pdf), in which the distributed key is the counterparty to any given messaging party, then to perform the decryption phase for the recipient, perform the Shamir recombination with the generator point swapped out with the sender's ephemeral public EC point.

**Comment by paulmillr** [comment]
What is the status of this? FC has dms now but they are not documented. Is this related: https://github.com/farcasterxyz/protocol/discussions/99 ?

**Comment by sds** [comment]
@paulmillr Not on the highest on the priority list but still something we are considering for the future. 

Going to close this issue in favor of the FIP proposed in #99.

**Comment by varunsrin** [comment]
@paulmillr we're planning to revisit this design closer to end of year 2024. the initial encrypted messaging design did not work as well as expected, so we need to rethink a new approach.

**Comment by paulmillr** [comment]
> the initial encrypted messaging design did not work as well as expected

any insights?

**Comment by varunsrin** [comment]
tl;dr is that double ratchet was hard to get right across the long tail of android devices in a react native environment with a small team (i.e. basically 1 person working on it). lots of hard to debug issues that broke messaging and caused people to stop using it. 

planning to revisit an encrypted system later this year once we have the basics working and a larger team ready to tackle it.

**Comment by paulmillr** [comment]
:(

**Comment by cboscolo** [comment]
That means we can leap frog over double ratchet and use the [triple ratchet variant in FIP99](https://github.com/farcasterxyz/protocol/discussions/99) :)

I'm curious to know if there is any community interest in adding experimental support for FIP99 to HUBs with a reference client lib? It could accelerate getting DC/GC supported in WC as well as other Farcaster clients like [Supercast](https://www.supercast.xyz/).

**Comment by CassOnMars** [comment]
Happy to lend deeper insights:

**Android**
- Android support for even basic cryptography is a bit rough, the long tail resulted in having to issue sharp cutoffs of Android versions (which turned out to be a wrong move as there were earlier ones that _could_ support it, but they were not stock Android)
- Export embargos also cropped up

**React Native**
React Native's native module support triggered a myriad of race conditions, forcing more and more of the implementation to get moved into native code. This was great for performance, but made support even more difficult for a small team to manage, especially with respect to cross-platform interop

**The Final Nail in the Coffin**
When extending support to web, we wanted a safer way to manage keys without requiring a separate client app on the desktop, and so we looked towards largeBlob support for storing some key material. This approach worked, until Google unceremoniously broke support for it in an update to Chrome. The official line was: profile user (i.e. not OS integration or HSM use) support for secret management should use PRF, but also PRF isn't supported for profiles yet, no ETA beyond "hopefully this year".

**Comment by cboscolo** [comment]
@CassOnMars what key material were you planning to share?
Having key material shared with a browser's context seems like an unsafe design decision to me?

**Comment by paulmillr** [comment]
@CassOnMars 

> Export embargos

wdym specifically?

**Comment by CassOnMars** [comment]
@cboscolo 
> Having key material shared with a browser's context seems like an unsafe design decision to me?

The double-ratchet implementation had unique keys to each device, guaranteed to belong to the user by virtue of having been signed by the Farcaster custody wallet, which lives on mobile. The browser itself was to hold the unique keys, to be accessible in only the direct casts context, obtained via interaction with webauthn (largeBlob/PRF, implementations would differ accordingly), and expunged when leaving that context. It is a tradeoff, yes, but one the user would choose to make if they wanted encrypted direct casts in the browser. This is a far safer option than, say, a portable inbox that is stored using a singular derived key and once compromised could be accessed anywhere, indefinitely.

@paulmillr 
> wdym specifically?
struggling to find the right error message again since it's been a while, but for compliance, versions of Android in certain countries have crippled their crypto library and would refuse to perform the requested AES-256-GCM operations

**Comment by paulmillr** [comment]
> would refuse to perform the requested AES-256-GCM operations

What about bundling wasm-sodium or something?

**Comment by cboscolo** [comment]
> This is a far safer option than, say, a portable inbox that is stored using a singular derived key and once compromised could be accessed anywhere, indefinitely.

Agree with this.
I was naively assuming you'd take a Signal-like approach and generate per-device encryption keys (also signed by the FC custody wallet.) [Direct Casts #99](https://github.com/farcasterxyz/protocol/discussions/99) takes this approach, right?
